New function "Select all" in popup menu of textarea
danstowell/jreepad pull request #4
Opened 2017-01-21 11:34 UTC by marcoM32

Hi jreepad Team,
I've added a new feature, now in the popup menu of textarea is present the "select all" function.
I have also reviewed the resource files.

Thanks and best regards
Marco

2017-01-22 19:17 UTC, danstowell requested changes
Thanks for this contribution. Looks good to me, just the whitespace needs fixing before merge

2017-01-22 19:17 UTC, danstowell commented on src/jreepad/editor/EditPopupHandler.java
> +	public static final String ITEM_SELECTALL = "selectall";
Here and elsewhere I see whitespace errors (tabs vs spaces). Could you please ensure your whitespace usage matches the rest of the file?

2017-01-22 19:17 UTC, danstowell commented on src/jreepad/lang/JreepadStrings.properties
> +AUTOSAVE_MINUTES=\ minutes
aha thanks

2017-01-23 09:10 UTC, marcoM32 reviewed
I apologize for that mistake, I corrected the problem.

regards
Marco

2017-01-23 21:40 UTC, danstowell approved these changes

2017-01-23 21:42 UTC, merged

2017-01-23 21:42 UTC, danstowell commented
Thank you